#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MasjidAdminApp
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MasjidDB")]
	public partial class MasjidDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertInventarisTable(InventarisTable instance);
    partial void UpdateInventarisTable(InventarisTable instance);
    partial void DeleteInventarisTable(InventarisTable instance);
    partial void InsertKegiatanTable(KegiatanTable instance);
    partial void UpdateKegiatanTable(KegiatanTable instance);
    partial void DeleteKegiatanTable(KegiatanTable instance);
    partial void InsertPemasukan(Pemasukan instance);
    partial void UpdatePemasukan(Pemasukan instance);
    partial void DeletePemasukan(Pemasukan instance);
    partial void InsertPengeluaran(Pengeluaran instance);
    partial void UpdatePengeluaran(Pengeluaran instance);
    partial void DeletePengeluaran(Pengeluaran instance);
    partial void InsertPengurusTable(PengurusTable instance);
    partial void UpdatePengurusTable(PengurusTable instance);
    partial void DeletePengurusTable(PengurusTable instance);
    partial void InsertUserTable(UserTable instance);
    partial void UpdateUserTable(UserTable instance);
    partial void DeleteUserTable(UserTable instance);
    #endregion
		
		public MasjidDBDataContext() : 
				base(global::MasjidAdminApp.Properties.Settings.Default.MasjidDBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MasjidDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasjidDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasjidDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MasjidDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<InventarisTable> InventarisTables
		{
			get
			{
				return this.GetTable<InventarisTable>();
			}
		}
		
		public System.Data.Linq.Table<KegiatanTable> KegiatanTables
		{
			get
			{
				return this.GetTable<KegiatanTable>();
			}
		}
		
		public System.Data.Linq.Table<Pemasukan> Pemasukans
		{
			get
			{
				return this.GetTable<Pemasukan>();
			}
		}
		
		public System.Data.Linq.Table<Pengeluaran> Pengeluarans
		{
			get
			{
				return this.GetTable<Pengeluaran>();
			}
		}
		
		public System.Data.Linq.Table<PengurusTable> PengurusTables
		{
			get
			{
				return this.GetTable<PengurusTable>();
			}
		}
		
		public System.Data.Linq.Table<UserTable> UserTables
		{
			get
			{
				return this.GetTable<UserTable>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.InventarisTable")]
	public partial class InventarisTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdBarang;
		
		private string _NamaBarang;
		
		private string _KategoriBarang;
		
		private System.DateTime _TanggalPembelian;
		
		private int _Jumlah;
		
		private string _Keterangan;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdBarangChanging(int value);
    partial void OnIdBarangChanged();
    partial void OnNamaBarangChanging(string value);
    partial void OnNamaBarangChanged();
    partial void OnKategoriBarangChanging(string value);
    partial void OnKategoriBarangChanged();
    partial void OnTanggalPembelianChanging(System.DateTime value);
    partial void OnTanggalPembelianChanged();
    partial void OnJumlahChanging(int value);
    partial void OnJumlahChanged();
    partial void OnKeteranganChanging(string value);
    partial void OnKeteranganChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public InventarisTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdBarang", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdBarang
		{
			get
			{
				return this._IdBarang;
			}
			set
			{
				if ((this._IdBarang != value))
				{
					this.OnIdBarangChanging(value);
					this.SendPropertyChanging();
					this._IdBarang = value;
					this.SendPropertyChanged("IdBarang");
					this.OnIdBarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaBarang", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NamaBarang
		{
			get
			{
				return this._NamaBarang;
			}
			set
			{
				if ((this._NamaBarang != value))
				{
					this.OnNamaBarangChanging(value);
					this.SendPropertyChanging();
					this._NamaBarang = value;
					this.SendPropertyChanged("NamaBarang");
					this.OnNamaBarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriBarang", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KategoriBarang
		{
			get
			{
				return this._KategoriBarang;
			}
			set
			{
				if ((this._KategoriBarang != value))
				{
					this.OnKategoriBarangChanging(value);
					this.SendPropertyChanging();
					this._KategoriBarang = value;
					this.SendPropertyChanged("KategoriBarang");
					this.OnKategoriBarangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalPembelian", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalPembelian
		{
			get
			{
				return this._TanggalPembelian;
			}
			set
			{
				if ((this._TanggalPembelian != value))
				{
					this.OnTanggalPembelianChanging(value);
					this.SendPropertyChanging();
					this._TanggalPembelian = value;
					this.SendPropertyChanged("TanggalPembelian");
					this.OnTanggalPembelianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Jumlah", DbType="Int NOT NULL")]
		public int Jumlah
		{
			get
			{
				return this._Jumlah;
			}
			set
			{
				if ((this._Jumlah != value))
				{
					this.OnJumlahChanging(value);
					this.SendPropertyChanging();
					this._Jumlah = value;
					this.SendPropertyChanged("Jumlah");
					this.OnJumlahChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Keterangan", DbType="NVarChar(255)")]
		public string Keterangan
		{
			get
			{
				return this._Keterangan;
			}
			set
			{
				if ((this._Keterangan != value))
				{
					this.OnKeteranganChanging(value);
					this.SendPropertyChanging();
					this._Keterangan = value;
					this.SendPropertyChanged("Keterangan");
					this.OnKeteranganChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KegiatanTable")]
	public partial class KegiatanTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdKegiatan;
		
		private string _NamaKegiatan;
		
		private System.DateTime _TanggalKegiatan;
		
		private string _Deskripsi;
		
		private string _PenanggungJawab;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdKegiatanChanging(int value);
    partial void OnIdKegiatanChanged();
    partial void OnNamaKegiatanChanging(string value);
    partial void OnNamaKegiatanChanged();
    partial void OnTanggalKegiatanChanging(System.DateTime value);
    partial void OnTanggalKegiatanChanged();
    partial void OnDeskripsiChanging(string value);
    partial void OnDeskripsiChanged();
    partial void OnPenanggungJawabChanging(string value);
    partial void OnPenanggungJawabChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public KegiatanTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdKegiatan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdKegiatan
		{
			get
			{
				return this._IdKegiatan;
			}
			set
			{
				if ((this._IdKegiatan != value))
				{
					this.OnIdKegiatanChanging(value);
					this.SendPropertyChanging();
					this._IdKegiatan = value;
					this.SendPropertyChanged("IdKegiatan");
					this.OnIdKegiatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaKegiatan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NamaKegiatan
		{
			get
			{
				return this._NamaKegiatan;
			}
			set
			{
				if ((this._NamaKegiatan != value))
				{
					this.OnNamaKegiatanChanging(value);
					this.SendPropertyChanging();
					this._NamaKegiatan = value;
					this.SendPropertyChanged("NamaKegiatan");
					this.OnNamaKegiatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalKegiatan", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalKegiatan
		{
			get
			{
				return this._TanggalKegiatan;
			}
			set
			{
				if ((this._TanggalKegiatan != value))
				{
					this.OnTanggalKegiatanChanging(value);
					this.SendPropertyChanging();
					this._TanggalKegiatan = value;
					this.SendPropertyChanged("TanggalKegiatan");
					this.OnTanggalKegiatanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Deskripsi", DbType="NVarChar(255)")]
		public string Deskripsi
		{
			get
			{
				return this._Deskripsi;
			}
			set
			{
				if ((this._Deskripsi != value))
				{
					this.OnDeskripsiChanging(value);
					this.SendPropertyChanging();
					this._Deskripsi = value;
					this.SendPropertyChanged("Deskripsi");
					this.OnDeskripsiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PenanggungJawab", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string PenanggungJawab
		{
			get
			{
				return this._PenanggungJawab;
			}
			set
			{
				if ((this._PenanggungJawab != value))
				{
					this.OnPenanggungJawabChanging(value);
					this.SendPropertyChanging();
					this._PenanggungJawab = value;
					this.SendPropertyChanged("PenanggungJawab");
					this.OnPenanggungJawabChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pemasukan")]
	public partial class Pemasukan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPemasukan;
		
		private System.DateTime _TanggalWaktuPemasukan;
		
		private string _SumberPemasukan;
		
		private string _NamaDonatur;
		
		private decimal _JumlahPemasukan;
		
		private string _KeteranganTambahan;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPemasukanChanging(int value);
    partial void OnIdPemasukanChanged();
    partial void OnTanggalWaktuPemasukanChanging(System.DateTime value);
    partial void OnTanggalWaktuPemasukanChanged();
    partial void OnSumberPemasukanChanging(string value);
    partial void OnSumberPemasukanChanged();
    partial void OnNamaDonaturChanging(string value);
    partial void OnNamaDonaturChanged();
    partial void OnJumlahPemasukanChanging(decimal value);
    partial void OnJumlahPemasukanChanged();
    partial void OnKeteranganTambahanChanging(string value);
    partial void OnKeteranganTambahanChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public Pemasukan()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPemasukan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPemasukan
		{
			get
			{
				return this._IdPemasukan;
			}
			set
			{
				if ((this._IdPemasukan != value))
				{
					this.OnIdPemasukanChanging(value);
					this.SendPropertyChanging();
					this._IdPemasukan = value;
					this.SendPropertyChanged("IdPemasukan");
					this.OnIdPemasukanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalWaktuPemasukan", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalWaktuPemasukan
		{
			get
			{
				return this._TanggalWaktuPemasukan;
			}
			set
			{
				if ((this._TanggalWaktuPemasukan != value))
				{
					this.OnTanggalWaktuPemasukanChanging(value);
					this.SendPropertyChanging();
					this._TanggalWaktuPemasukan = value;
					this.SendPropertyChanged("TanggalWaktuPemasukan");
					this.OnTanggalWaktuPemasukanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SumberPemasukan", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SumberPemasukan
		{
			get
			{
				return this._SumberPemasukan;
			}
			set
			{
				if ((this._SumberPemasukan != value))
				{
					this.OnSumberPemasukanChanging(value);
					this.SendPropertyChanging();
					this._SumberPemasukan = value;
					this.SendPropertyChanged("SumberPemasukan");
					this.OnSumberPemasukanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaDonatur", DbType="NVarChar(100)")]
		public string NamaDonatur
		{
			get
			{
				return this._NamaDonatur;
			}
			set
			{
				if ((this._NamaDonatur != value))
				{
					this.OnNamaDonaturChanging(value);
					this.SendPropertyChanging();
					this._NamaDonatur = value;
					this.SendPropertyChanged("NamaDonatur");
					this.OnNamaDonaturChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahPemasukan", DbType="Decimal(18,2) NOT NULL")]
		public decimal JumlahPemasukan
		{
			get
			{
				return this._JumlahPemasukan;
			}
			set
			{
				if ((this._JumlahPemasukan != value))
				{
					this.OnJumlahPemasukanChanging(value);
					this.SendPropertyChanging();
					this._JumlahPemasukan = value;
					this.SendPropertyChanged("JumlahPemasukan");
					this.OnJumlahPemasukanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeteranganTambahan", DbType="NVarChar(255)")]
		public string KeteranganTambahan
		{
			get
			{
				return this._KeteranganTambahan;
			}
			set
			{
				if ((this._KeteranganTambahan != value))
				{
					this.OnKeteranganTambahanChanging(value);
					this.SendPropertyChanging();
					this._KeteranganTambahan = value;
					this.SendPropertyChanged("KeteranganTambahan");
					this.OnKeteranganTambahanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pengeluaran")]
	public partial class Pengeluaran : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPengeluaran;
		
		private System.DateTime _TanggalWaktuPengeluaran;
		
		private string _KategoriPengeluaran;
		
		private decimal _JumlahPengeluaran;
		
		private string _KeteranganTambahan;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPengeluaranChanging(int value);
    partial void OnIdPengeluaranChanged();
    partial void OnTanggalWaktuPengeluaranChanging(System.DateTime value);
    partial void OnTanggalWaktuPengeluaranChanged();
    partial void OnKategoriPengeluaranChanging(string value);
    partial void OnKategoriPengeluaranChanged();
    partial void OnJumlahPengeluaranChanging(decimal value);
    partial void OnJumlahPengeluaranChanged();
    partial void OnKeteranganTambahanChanging(string value);
    partial void OnKeteranganTambahanChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public Pengeluaran()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengeluaran", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPengeluaran
		{
			get
			{
				return this._IdPengeluaran;
			}
			set
			{
				if ((this._IdPengeluaran != value))
				{
					this.OnIdPengeluaranChanging(value);
					this.SendPropertyChanging();
					this._IdPengeluaran = value;
					this.SendPropertyChanged("IdPengeluaran");
					this.OnIdPengeluaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TanggalWaktuPengeluaran", DbType="DateTime NOT NULL")]
		public System.DateTime TanggalWaktuPengeluaran
		{
			get
			{
				return this._TanggalWaktuPengeluaran;
			}
			set
			{
				if ((this._TanggalWaktuPengeluaran != value))
				{
					this.OnTanggalWaktuPengeluaranChanging(value);
					this.SendPropertyChanging();
					this._TanggalWaktuPengeluaran = value;
					this.SendPropertyChanged("TanggalWaktuPengeluaran");
					this.OnTanggalWaktuPengeluaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KategoriPengeluaran", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string KategoriPengeluaran
		{
			get
			{
				return this._KategoriPengeluaran;
			}
			set
			{
				if ((this._KategoriPengeluaran != value))
				{
					this.OnKategoriPengeluaranChanging(value);
					this.SendPropertyChanging();
					this._KategoriPengeluaran = value;
					this.SendPropertyChanged("KategoriPengeluaran");
					this.OnKategoriPengeluaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JumlahPengeluaran", DbType="Decimal(18,2) NOT NULL")]
		public decimal JumlahPengeluaran
		{
			get
			{
				return this._JumlahPengeluaran;
			}
			set
			{
				if ((this._JumlahPengeluaran != value))
				{
					this.OnJumlahPengeluaranChanging(value);
					this.SendPropertyChanging();
					this._JumlahPengeluaran = value;
					this.SendPropertyChanged("JumlahPengeluaran");
					this.OnJumlahPengeluaranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KeteranganTambahan", DbType="NVarChar(255)")]
		public string KeteranganTambahan
		{
			get
			{
				return this._KeteranganTambahan;
			}
			set
			{
				if ((this._KeteranganTambahan != value))
				{
					this.OnKeteranganTambahanChanging(value);
					this.SendPropertyChanging();
					this._KeteranganTambahan = value;
					this.SendPropertyChanged("KeteranganTambahan");
					this.OnKeteranganTambahanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PengurusTable")]
	public partial class PengurusTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdPengurus;
		
		private string _NamaPengurus;
		
		private string _JabatanPengurus;
		
		private string _KontakPengurus;
		
		private string _AlamatPengurus;
		
		private System.Nullable<int> _UserID;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdPengurusChanging(int value);
    partial void OnIdPengurusChanged();
    partial void OnNamaPengurusChanging(string value);
    partial void OnNamaPengurusChanged();
    partial void OnJabatanPengurusChanging(string value);
    partial void OnJabatanPengurusChanged();
    partial void OnKontakPengurusChanging(string value);
    partial void OnKontakPengurusChanged();
    partial void OnAlamatPengurusChanging(string value);
    partial void OnAlamatPengurusChanged();
    partial void OnUserIDChanging(System.Nullable<int> value);
    partial void OnUserIDChanged();
    #endregion
		
		public PengurusTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdPengurus", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdPengurus
		{
			get
			{
				return this._IdPengurus;
			}
			set
			{
				if ((this._IdPengurus != value))
				{
					this.OnIdPengurusChanging(value);
					this.SendPropertyChanging();
					this._IdPengurus = value;
					this.SendPropertyChanged("IdPengurus");
					this.OnIdPengurusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NamaPengurus", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NamaPengurus
		{
			get
			{
				return this._NamaPengurus;
			}
			set
			{
				if ((this._NamaPengurus != value))
				{
					this.OnNamaPengurusChanging(value);
					this.SendPropertyChanging();
					this._NamaPengurus = value;
					this.SendPropertyChanged("NamaPengurus");
					this.OnNamaPengurusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_JabatanPengurus", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string JabatanPengurus
		{
			get
			{
				return this._JabatanPengurus;
			}
			set
			{
				if ((this._JabatanPengurus != value))
				{
					this.OnJabatanPengurusChanging(value);
					this.SendPropertyChanging();
					this._JabatanPengurus = value;
					this.SendPropertyChanged("JabatanPengurus");
					this.OnJabatanPengurusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KontakPengurus", DbType="NVarChar(50)")]
		public string KontakPengurus
		{
			get
			{
				return this._KontakPengurus;
			}
			set
			{
				if ((this._KontakPengurus != value))
				{
					this.OnKontakPengurusChanging(value);
					this.SendPropertyChanging();
					this._KontakPengurus = value;
					this.SendPropertyChanged("KontakPengurus");
					this.OnKontakPengurusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AlamatPengurus", DbType="NVarChar(200)")]
		public string AlamatPengurus
		{
			get
			{
				return this._AlamatPengurus;
			}
			set
			{
				if ((this._AlamatPengurus != value))
				{
					this.OnAlamatPengurusChanging(value);
					this.SendPropertyChanging();
					this._AlamatPengurus = value;
					this.SendPropertyChanged("AlamatPengurus");
					this.OnAlamatPengurusChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", DbType="Int")]
		public System.Nullable<int> UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserTable")]
	public partial class UserTable : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _UserID;
		
		private string _Username;
		
		private string _FullName;
		
		private string _Password;
		
		private string _UniqueCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserIDChanging(int value);
    partial void OnUserIDChanged();
    partial void OnUsernameChanging(string value);
    partial void OnUsernameChanged();
    partial void OnFullNameChanging(string value);
    partial void OnFullNameChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnUniqueCodeChanging(string value);
    partial void OnUniqueCodeChanged();
    #endregion
		
		public UserTable()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Username", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Username
		{
			get
			{
				return this._Username;
			}
			set
			{
				if ((this._Username != value))
				{
					this.OnUsernameChanging(value);
					this.SendPropertyChanging();
					this._Username = value;
					this.SendPropertyChanged("Username");
					this.OnUsernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FullName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string FullName
		{
			get
			{
				return this._FullName;
			}
			set
			{
				if ((this._FullName != value))
				{
					this.OnFullNameChanging(value);
					this.SendPropertyChanging();
					this._FullName = value;
					this.SendPropertyChanged("FullName");
					this.OnFullNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UniqueCode", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string UniqueCode
		{
			get
			{
				return this._UniqueCode;
			}
			set
			{
				if ((this._UniqueCode != value))
				{
					this.OnUniqueCodeChanging(value);
					this.SendPropertyChanging();
					this._UniqueCode = value;
					this.SendPropertyChanged("UniqueCode");
					this.OnUniqueCodeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
